apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}
  labels:
    #enabled for Spring Cloud Kubernetes Configuration Watcher
    spring.cloud.kubernetes.config: "true"
data:
  application.properties: |-
    s1p.decorate=true