apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}
  labels:
    ##support configmap changes supported by configwatcher
    spring.cloud.kubernetes.config: "true"
data:
  application.properties: |-
    s1p.decorate=true